name: 'Buy me a coffee messages -> Readme'
author: 'Akos Balasko'
description: ''

inputs:
  BUY-ME-A-COFFEE-TOKEN:  # id of input
    description: 'Your Buy me a coffee token'
    required: true
  
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    default: ${{ github.token }}
    required: true

  REPOSITORY:
    description: "Your GitHub repository"
    default: ${{ github.repository }}
    required: false

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Buy me a Coffee messages updated"
    required: false

  number-of-messages: 
    description: 'Number of the messages to show'
    default: 3

runs:
  using: 'node16'
  main: 'lib/main.js'

branding:
  icon: "info"
  color: "blue"
