name: 'Buy me a coffee messages -> Readme'
author: 'Akos Balasko'
description: ''

inputs:
  BUY_ME_A_COFFEE_TOKEN:  # id of input
    description: 'Your Buy me a coffee token'
    required: true
  
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    default: ${{ github.token }}
    required: true

  REPOSITORY:
    description: "Your GitHub repository"
    default: ${{ github.repository }}
    required: false

  COMMIT_MESSAGE:
    description: "Add a commit message of your choice"
    default: "Buy me a Coffee messages updated"
    required: false

  NUMBER_OF_MESSAGES: 
    description: 'Number of the messages to show'
    default: 3

  BRANCH:
    description: 'Branch to be updated'
    default: main


runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: "info"
  color: "blue"
