name: 'buy-me-a-coffee'
author: 'Akos Balasko'
description: ''

inputs:
  GH_TOKEN:
    description: "GitHub access token with Repo scope"
    default: ${{ github.token }}
    required: true

  BUY_ME_A_COFFEE_TOKEN:  # id of input
    description: 'Your Buy me a coffee token'
    required: true

  NUMBER_OF_MESSAGES: 
    description: 'Number of the messages to show'
    default: 3

  REPOSITORY:
    description: "Your GitHub repository"
    default: ${{ github.repository }}
    required: false

runs:
  using: 'node16'
  main: './../../../dist/index.js'
