name: 'Buy me a coffee messages -> Readme'
author: 'Akos Balasko'
description: ''

inputs:
  BUY_ME_A_COFFEE_TOKEN:  # id of input
    description: 'Your Buy me a coffee token'
    required: true

  NUMBER_OF_MESSAGES: 
    description: 'Number of the messages to show'
    default: 3

output:
  MESSAGES_HTML:
    description: 'The latest X messages formatted'

runs:
  using: 'node16'
  main: 'dist/index.js'
